### ISSUE TITLE
AttributeError: 'DiGraph' object has no attribute 'node' when running 

### ISSUE THREAD

**Issue by explcre** [ebranlard/matlab2python#14]
I    runned "pip install -e . "to install this and run 
"smop xxx.m"
to run smop, but I met this problem.

> /home/explcre/anaconda3/lib/python3.9/site-packages/ply/lex.py:760: FutureWarning: Possible nested set at position 65
  c = re.compile('(?P<%s>%s)' % (fname, _get_regex(f)), self.reflags)
/home/explcre/anaconda3/lib/python3.9/site-packages/ply/lex.py:498: FutureWarning: Possible nested set at position 118
  lexre = re.compile(regex, reflags)
str
Traceback (most recent call last):
  File "/mnt/f/Downloads/smop-master/smop-master/smop/main.py", line 66, in main
    G = resolve.resolve(stmt_list)
  File "/mnt/f/Downloads/smop-master/smop-master/smop/resolve.py", line 54, in resolve
    u = G.node[n]["ident"]
AttributeError: 'DiGraph' object has no attribute 'node'
Errors: 1

Would you please tell me how to fix it?

**Comment by explcre** [comment]
wrong place, sorry
