### ISSUE TITLE
Can't Find Parser.py

### ISSUE THREAD

**Issue by coletrane8646** [ebranlard/matlab2python#5]
After following the installation steps outlined, I receive this error when trying to run:
python matlab2python.py file file.m -o file.py

(smop) c:\Users\user\Downloads\matlab2python-master>python matlab2python.py file pset3.m
Traceback (most recent call last):
  File "matlab2python.py", line 49, in <module>
    main(sys.argv[1:])
  File "matlab2python.py", line 44, in main
    mparser.matlab2python(opts.filelist,opts)
  File "c:\Users\user\Downloads\matlab2python-master\matlabparser\parser.py", line 433, in matlab2python
    matlab2python(f,opts)
  File "c:\Users\user\Downloads\matlab2python-master\matlabparser\parser.py", line 436, in matlab2python
    raise Exception('FileNotFound:'+filename)
Exception: FileNotFound:file

The folder structure is the exact same as it is on GitHub... what did I do wrong?

**Comment by ebranlard** [comment]
Hi @coletrane8646 
I seems you are calling with the wrong syntax, no? The syntax should be:

```
python matlab2python.py file.m -o file.py
```

**Comment by ebranlard** [comment]
I'm closing this issue, feel free to reopen if you still have problems.
