### ISSUE TITLE
parse.py: name 'ret_expr' is not defined

### ISSUE THREAD

**Issue by leuliett** [ebranlard/matlab2python#6]
WARNING: Token 'CLASSDEF' defined, but not used
WARNING: Token 'END_UNEXPECTED' defined, but not used
WARNING: There are 2 unused tokens
Generating LALR tables
/temp/env/lib/python3.10/site-packages/ply/lex.py:760: FutureWarning: Possible nested set at position 65
  c = re.compile('(?P<%s>%s)' % (fname, _get_regex(f)), self.reflags)
/temp/env/lib/python3.10/site-packages/ply/lex.py:498: FutureWarning: Possible nested set at position 118
  lexre = re.compile(regex, reflags)
Traceback (most recent call last):
  File "/temp/env/lib/python3.10/site-packages/smop/main.py", line 61, in main
    stmt_list = parse.parse(buf if buf[-1] == '\n' else buf + '\n')
  File "/temp/env/lib/python3.10/site-packages/smop/parse.py", line 849, in parse
    p = parser.parse(
  File "/temp/env/lib/python3.10/site-packages/ply/yacc.py", line 331, in parse
    return self.parseopt(input, lexer, debug, tracking, tokenfunc)
  File "/temp/env/lib/python3.10/site-packages/ply/yacc.py", line 823, in parseopt
    p.callable(pslice)
  File "/temp/env/lib/python3.10/site-packages/smop/parse.py", line 696, in p_return_stmt
    p[0] = node.return_stmt(ret=ret_expr)
NameError: name 'ret_expr' is not defined
Errors: 1

**Comment by ebranlard** [comment]
Hi @leuliett, 
Could you share the matlab code on which the code is failing? 
If possible, try to reduce it to few lines that still reproduce the errors your sent above. 
Thanks!

**Comment by leuliett** [comment]
Thanks for following up. I was attempting to use smop.py directly. matlab2python.py is working for me, so I'm closing the issue.
